server:
  port: 8020
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback-stream
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true