server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule