server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001