server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001
#ribon:
#  eager-load:
#    enabled: true
#    clients: client1,client2

#<clientName>.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
#<clientName>.ribbon.listOfServers=localhost:8000,localhost:8001