server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#feign:
#  client:
#    config:
#      microservice-provider-user:
#        loggerLevel: full
logging:
  level:
    # 将Feign接口的日志级别设置成DEBUG，因为Feigh的Logger.Level只对DEBUG做出响应
    com.baichen.cloud.microserviceconsumermoviefeignlogging.user.feign.UserFeignClient: DEBUG